export interface RouteContextEntry {
  route: string;
  title: string;
  audience: string;
  owner: string;
  purpose: string;
  overlapNotes: string;
  level?: "manager" | "project" | "payload" | "run" | "system";
}

export const ROUTE_CONTEXT_INVENTORY: RouteContextEntry[] = [
  {
    route: "/",
    title: "Root Redirect",
    audience: "All operators",
    owner: "platform-operations",
    purpose: "Redirects the app root into the manager command center.",
    overlapNotes: "Canonical entry uses `/home`.",
    level: "manager",
  },
  {
    route: "/home",
    title: "Home",
    audience: "Operators and maintainers",
    owner: "platform-operations",
    purpose: "Manager command center for the Moradins Harness repo, tracked portfolio, approvals, payload readiness, and next actions.",
    overlapNotes: "Project-scoped work happens under `/project/:projectId/*`.",
    level: "manager",
  },
  {
    route: "/projects",
    title: "Projects",
    audience: "Operators and maintainers",
    owner: "platform-operations",
    purpose: "Portfolio surface for tracked repos, project selection, deploy posture, and project opening actions.",
    overlapNotes: "Detailed repo work moves into `/project/:projectId/*`.",
    level: "manager",
  },
  {
    route: "/deploy",
    title: "Deploy",
    audience: "Setup operators",
    owner: "platform-operations",
    purpose: "Parent workspace for guided deploy and import flows.",
    overlapNotes: "Child routes carry the concrete workflow stages.",
    level: "run",
  },
  {
    route: "/deploy/quick-start",
    title: "Quick Start",
    audience: "New operators",
    owner: "platform-operations",
    purpose: "Guided first-run onboarding path before deploy visualization and builder execution.",
    overlapNotes: "Raw markdown remains available in Docs.",
    level: "run",
  },
  {
    route: "/deploy/map",
    title: "Deploy Map",
    audience: "Setup operators and reviewers",
    owner: "platform-operations",
    purpose: "Visual explanation of what Moradin deploys, what is prefilled by the payload, and where operator or scan data changes the output.",
    overlapNotes: "Builder remains the guarded execution surface.",
    level: "run",
  },
  {
    route: "/deploy/readiness",
    title: "Readiness",
    audience: "Setup operators",
    owner: "platform-operations",
    purpose: "Request-only host tooling checks, install request artifacts, and repo registry summaries before deploy work.",
    overlapNotes: "System status remains the lower-level diagnostics page.",
    level: "run",
  },
  {
    route: "/deploy/builder",
    title: "Deploy Builder",
    audience: "Setup operators",
    owner: "platform-operations",
    purpose: "Create or import destination repos and run discovery, generation, and guarded deploy workflows.",
    overlapNotes: "Verification surfaces live in deploy status and settings/system.",
    level: "run",
  },
  {
    route: "/deploy/status",
    title: "Deploy Verification",
    audience: "Delivery leads and integration operators",
    owner: "platform-operations",
    purpose: "Critical-first integration report for established projects after sidecar deploy and discovery synthesis.",
    overlapNotes: "Project operations also expose status from the project workspace.",
    level: "run",
  },
  {
    route: "/payload",
    title: "Moradin Payload",
    audience: "Harness maintainers",
    owner: "platform-architecture",
    purpose: "Moradin payload workspace for compatibility status, coverage, and deployment-safe structure inspection.",
    overlapNotes: "Payload execution still routes through Deploy workspace.",
    level: "payload",
  },
  {
    route: "/template",
    title: "Payload Redirect",
    audience: "Harness maintainers",
    owner: "platform-architecture",
    purpose: "Compatibility redirect into the Moradin payload workspace.",
    overlapNotes: "Canonical navigation should use `/payload`.",
    level: "payload",
  },
  {
    route: "/project/:projectId",
    title: "Project Workspace",
    audience: "Operators and reviewers",
    owner: "platform-operations",
    purpose: "Parent workspace for one selected project or the manager repo operating as a project target.",
    overlapNotes: "Child routes carry the actual project sub-workspaces.",
    level: "project",
  },
  {
    route: "/project/:projectId/overview",
    title: "Project Overview",
    audience: "Operators and reviewers",
    owner: "platform-operations",
    purpose: "Operational summary for one selected project with docs, phases, runs, guidance, and next-step context.",
    overlapNotes: "Manager-level portfolio work stays in `/home` and `/projects`.",
    level: "project",
  },
  {
    route: "/project/:projectId/delivery",
    title: "Project Delivery Redirect",
    audience: "Delivery leads",
    owner: "platform-operations",
    purpose: "Redirect surface into canonical delivery views.",
    overlapNotes: "Use features or phases child routes directly.",
    level: "project",
  },
  {
    route: "/project/:projectId/delivery/features",
    title: "Delivery Features",
    audience: "Delivery leads",
    owner: "platform-operations",
    purpose: "Feature implementation view within the project delivery workspace.",
    overlapNotes: "Phase detail is split into the sibling phases route during transition.",
    level: "project",
  },
  {
    route: "/project/:projectId/delivery/phases",
    title: "Delivery Phases",
    audience: "Program managers",
    owner: "platform-operations",
    purpose: "Phase and stage backlog parsed from implementation phases with checklist-level completion and done-when criteria.",
    overlapNotes: "Feature detail remains in the sibling features route during transition.",
    level: "project",
  },
  {
    route: "/project/:projectId/governance",
    title: "Governance",
    audience: "Governance owners",
    owner: "platform-operations",
    purpose: "Domain health from harness docs: security, interfaces, architecture, observability, operations, and governance.",
    overlapNotes: "Detailed routing relationships live in topology views.",
    level: "project",
  },
  {
    route: "/project/:projectId/topology",
    title: "Topology Redirect",
    audience: "Architecture and delivery teams",
    owner: "platform-architecture",
    purpose: "Redirect surface into canonical topology modes.",
    overlapNotes: "Use project, harness, or combined child routes directly.",
    level: "project",
  },
  {
    route: "/project/:projectId/topology/project",
    title: "Project Topology",
    audience: "Architecture and delivery teams",
    owner: "platform-architecture",
    purpose: "Project-facing topology for mission, objective alignment, and service ownership boundaries.",
    overlapNotes: "Harness topology focuses on control-plane behavior.",
    level: "project",
  },
  {
    route: "/project/:projectId/topology/harness",
    title: "Harness Topology",
    audience: "Harness maintainers",
    owner: "platform-architecture",
    purpose: "Harness observability for loop controls, gates, artifacts, approvals, and policy routing behavior.",
    overlapNotes: "Combined topology unifies both perspectives.",
    level: "project",
  },
  {
    route: "/project/:projectId/topology/combined",
    title: "Combined Topology",
    audience: "Architecture reviewers",
    owner: "platform-architecture",
    purpose: "Combined routing view joining project services, harness controls, and connected topology surfaces.",
    overlapNotes: "Project and harness single-mode views remain available as sibling routes.",
    level: "project",
  },
  {
    route: "/project/:projectId/docs",
    title: "Project Docs",
    audience: "All operators",
    owner: "platform-operations",
    purpose: "Project-scoped entry into docs exploration and truth-layer review.",
    overlapNotes: "Global docs explorer remains at `/docs`.",
    level: "project",
  },
  {
    route: "/project/:projectId/operations",
    title: "Operations Redirect",
    audience: "Operators and reviewers",
    owner: "platform-operations",
    purpose: "Redirect surface into canonical operations views.",
    overlapNotes: "Use loops or status child routes directly.",
    level: "project",
  },
  {
    route: "/project/:projectId/operations/loops",
    title: "Loop Processes",
    audience: "Operators and reviewers",
    owner: "platform-operations",
    purpose: "Estimated loop runway, blockers, and execution readiness captured at cycle closeout.",
    overlapNotes: "Project verification remains in the sibling status route.",
    level: "project",
  },
  {
    route: "/project/:projectId/operations/status",
    title: "Project Status",
    audience: "Delivery leads and integration operators",
    owner: "platform-operations",
    purpose: "Project verification status inside the project operations workspace.",
    overlapNotes: "Deploy workspace exposes the same surface during guided execution.",
    level: "project",
  },
  {
    route: "/reviews",
    title: "Reviews",
    audience: "Human reviewers",
    owner: "platform-operations",
    purpose: "Parent workspace for approvals, review queue, change visibility, and archived evidence.",
    overlapNotes: "Child routes hold the concrete review surfaces.",
    level: "run",
  },
  {
    route: "/reviews/queue",
    title: "Review Queue",
    audience: "Human reviewers",
    owner: "platform-operations",
    purpose: "Structured review summary for both project and harness decisions without opening raw markdown first.",
    overlapNotes: "Detailed change surfaces remain in sibling review routes.",
    level: "run",
  },
  {
    route: "/reviews/changes",
    title: "Change Feed",
    audience: "Maintainers",
    owner: "platform-operations",
    purpose: "Working tree and markdown change visibility for the active branch and review cycle.",
    overlapNotes: "Approval state remains in review queue and activity.",
    level: "run",
  },
  {
    route: "/reviews/exchange",
    title: "Activity",
    audience: "Reviewers and maintainers",
    owner: "platform-operations",
    purpose: "Rolling change feed for current governed work, release insights, and recent review activity.",
    overlapNotes: "Review Queue is the high-level decision surface.",
    level: "run",
  },
  {
    route: "/reviews/archive",
    title: "Archive",
    audience: "Reviewers",
    owner: "platform-operations",
    purpose: "Structured archive records for suggestions, updates, and upgrade-review outcomes.",
    overlapNotes: "Actionable items should move back into active review surfaces.",
    level: "run",
  },
  {
    route: "/docs",
    title: "Docs Explorer",
    audience: "All operators",
    owner: "platform-operations",
    purpose: "Search, metadata, and browsing for docs and skills inventory.",
    overlapNotes: "Project workspace docs route provides project-scoped entry.",
    level: "manager",
  },
  {
    route: "/docs/:docId",
    title: "Doc Detail",
    audience: "All operators",
    owner: "platform-operations",
    purpose: "Detailed markdown drill-down for a selected document.",
    overlapNotes: "Review decisions should not require opening raw markdown first.",
    level: "manager",
  },
  {
    route: "/settings",
    title: "Settings",
    audience: "End users",
    owner: "platform-operations",
    purpose: "Parent workspace for preferences, diagnostics, and help.",
    overlapNotes: "Child routes hold the concrete settings surfaces.",
    level: "system",
  },
  {
    route: "/settings/preferences",
    title: "Preferences",
    audience: "End users",
    owner: "platform-operations",
    purpose: "Visual preferences plus non-secret operational defaults for builder, SSH, and assistant actions.",
    overlapNotes: "System diagnostics remain in the sibling system route.",
    level: "system",
  },
  {
    route: "/settings/system",
    title: "System Status",
    audience: "Operations and maintainers",
    owner: "platform-operations",
    purpose: "Operational diagnostics and connection checks before builder or deploy work starts.",
    overlapNotes: "Deploy verification remains in deploy/project status routes.",
    level: "system",
  },
  {
    route: "/settings/help",
    title: "Help",
    audience: "New and returning operators",
    owner: "platform-operations",
    purpose: "Canonical guidance and workflow map for harness operations.",
    overlapNotes: "Structured decisions route into Reviews.",
    level: "system",
  },
  {
    route: "/quick-start",
    title: "Quick Start Alias",
    audience: "New operators",
    owner: "platform-operations",
    purpose: "Legacy redirect into the canonical deploy quick-start route.",
    overlapNotes: "Canonical navigation should use `/deploy/quick-start`.",
    level: "run",
  },
  {
    route: "/readiness",
    title: "Readiness Alias",
    audience: "Setup operators",
    owner: "platform-operations",
    purpose: "Legacy redirect into the canonical deploy readiness route.",
    overlapNotes: "Canonical navigation should use `/deploy/readiness`.",
    level: "run",
  },
  {
    route: "/deploy-map",
    title: "Deploy Map Alias",
    audience: "Setup operators and reviewers",
    owner: "platform-operations",
    purpose: "Legacy redirect into the canonical deploy map route.",
    overlapNotes: "Canonical navigation should use `/deploy/map`.",
    level: "run",
  },
  {
    route: "/builder",
    title: "Builder Alias",
    audience: "Setup operators",
    owner: "platform-operations",
    purpose: "Legacy redirect into the canonical deploy builder route.",
    overlapNotes: "Canonical navigation should use `/deploy/builder`.",
    level: "run",
  },
  {
    route: "/project-status",
    title: "Project Status Alias",
    audience: "Delivery leads and integration operators",
    owner: "platform-operations",
    purpose: "Legacy redirect into the canonical deploy verification route.",
    overlapNotes: "Canonical navigation should use `/deploy/status` or project operations status.",
    level: "run",
  },
  {
    route: "/system-status",
    title: "System Status Alias",
    audience: "Operations and maintainers",
    owner: "platform-operations",
    purpose: "Legacy redirect into canonical settings/system diagnostics.",
    overlapNotes: "Canonical navigation should use `/settings/system`.",
    level: "system",
  },
  {
    route: "/help",
    title: "Help Alias",
    audience: "New and returning operators",
    owner: "platform-operations",
    purpose: "Legacy redirect into canonical help routing.",
    overlapNotes: "Canonical navigation should use `/settings/help`.",
    level: "system",
  },
  {
    route: "/review",
    title: "Review Alias",
    audience: "Human reviewers",
    owner: "platform-operations",
    purpose: "Legacy redirect into canonical review queue routing.",
    overlapNotes: "Canonical navigation should use `/reviews/queue`.",
    level: "run",
  },
  {
    route: "/changes",
    title: "Changes Alias",
    audience: "Maintainers",
    owner: "platform-operations",
    purpose: "Legacy redirect into canonical change-feed routing.",
    overlapNotes: "Canonical navigation should use `/reviews/changes`.",
    level: "run",
  },
  {
    route: "/exchange",
    title: "Activity Alias",
    audience: "Reviewers and maintainers",
    owner: "platform-operations",
    purpose: "Legacy redirect into canonical activity routing.",
    overlapNotes: "Canonical navigation should use `/reviews/exchange`.",
    level: "run",
  },
  {
    route: "/archive",
    title: "Archive Alias",
    audience: "Reviewers",
    owner: "platform-operations",
    purpose: "Legacy redirect into canonical archive routing.",
    overlapNotes: "Canonical navigation should use `/reviews/archive`.",
    level: "run",
  },
  {
    route: "/effects",
    title: "Activity Alias",
    audience: "Reviewers and maintainers",
    owner: "platform-operations",
    purpose: "Legacy redirect into canonical activity routing.",
    overlapNotes: "Canonical navigation should use `/reviews/exchange`.",
    level: "run",
  },
  {
    route: "/features",
    title: "Features Alias",
    audience: "Delivery leads",
    owner: "platform-operations",
    purpose: "Legacy redirect into the selected project delivery/features view.",
    overlapNotes: "Canonical navigation should use `/project/:projectId/delivery/features`.",
    level: "project",
  },
  {
    route: "/phases",
    title: "Phases Alias",
    audience: "Program managers",
    owner: "platform-operations",
    purpose: "Legacy redirect into the selected project delivery/phases view.",
    overlapNotes: "Canonical navigation should use `/project/:projectId/delivery/phases`.",
    level: "project",
  },
  {
    route: "/policies",
    title: "Governance Alias",
    audience: "Governance owners",
    owner: "platform-operations",
    purpose: "Legacy redirect into the selected project governance workspace.",
    overlapNotes: "Canonical navigation should use `/project/:projectId/governance`.",
    level: "project",
  },
  {
    route: "/project-topology",
    title: "Project Topology Alias",
    audience: "Architecture and delivery teams",
    owner: "platform-architecture",
    purpose: "Legacy redirect into the selected project topology/project view.",
    overlapNotes: "Canonical navigation should use `/project/:projectId/topology/project`.",
    level: "project",
  },
  {
    route: "/harness-topology",
    title: "Harness Topology Alias",
    audience: "Harness maintainers",
    owner: "platform-architecture",
    purpose: "Legacy redirect into the selected project topology/harness view.",
    overlapNotes: "Canonical navigation should use `/project/:projectId/topology/harness`.",
    level: "project",
  },
  {
    route: "/topology",
    title: "Combined Topology Alias",
    audience: "Architecture reviewers",
    owner: "platform-architecture",
    purpose: "Legacy redirect into the selected project topology/combined view.",
    overlapNotes: "Canonical navigation should use `/project/:projectId/topology/combined`.",
    level: "project",
  },
  {
    route: "/cycles",
    title: "Loop Processes Alias",
    audience: "Operators and reviewers",
    owner: "platform-operations",
    purpose: "Legacy redirect into the selected project operations/loops view.",
    overlapNotes: "Canonical navigation should use `/project/:projectId/operations/loops`.",
    level: "project",
  },
  {
    route: "/loop-processes",
    title: "Loop Processes Alias",
    audience: "Operators and reviewers",
    owner: "platform-operations",
    purpose: "Legacy redirect into the selected project operations/loops view.",
    overlapNotes: "Canonical navigation should use `/project/:projectId/operations/loops`.",
    level: "project",
  },
];
