# Generated by .templates/scripts/render/render_repo_adapters.py. Edit central templates, then re-render.
.PHONY: repo-brief verify-fast verify verify-security review-ready verify-ci ci-local bootstrap-ci bootstrap-security verify-paths fix-paths-safe push-gate release-gate-local sonarqube-local verify-ui-cli

repo-brief:
	@./tooling/bin/repo-brief.sh

verify-fast:
	@./tooling/bin/verify-fast.sh

verify:
	@./tooling/bin/verify.sh

verify-security:
	@./tooling/bin/verify-security.sh

review-ready:
	@./tooling/bin/review-ready.sh

verify-ci:
	@./tooling/bin/verify-ci.sh

ci-local:
	@./tooling/bin/ci-local.sh

bootstrap-ci:
	@./tooling/bin/bootstrap-ci.sh

bootstrap-security:
	@./tooling/bin/bootstrap-security.sh

verify-paths:
	@./tooling/bin/verify-paths.sh

fix-paths-safe:
	@./tooling/bin/fix-paths-safe.sh

push-gate:
	@./tooling/bin/push-gate.sh

release-gate-local:
	@./tooling/bin/release-gate-local.sh

sonarqube-local:
	@./tooling/bin/sonarqube-local.sh

verify-ui-cli:
	@./tooling/bin/verify-ui-cli.sh
