# Generated by shared-tooling-source/scripts/render/render_repo_adapters.py. Edit central templates, then re-render.
.PHONY: repo-brief verify-fast verify verify-security review-ready verify-ci ci-local bootstrap-ci bootstrap-security verify-paths fix-paths-safe verify-ui-cli builder-brief adoption-brief release-brief new-repo-brief onboarding-brief

repo-brief:
	@./tooling/bin/repo-brief.sh

verify-fast:
	@./tooling/bin/verify-fast.sh

verify:
	@./tooling/bin/verify.sh

verify-security:
	@./tooling/bin/verify-security.sh

review-ready:
	@./tooling/bin/review-ready.sh

verify-ci:
	@./tooling/bin/verify-ci.sh

ci-local:
	@./tooling/bin/ci-local.sh

bootstrap-ci:
	@./tooling/bin/bootstrap-ci.sh

bootstrap-security:
	@./tooling/bin/bootstrap-security.sh

verify-paths:
	@./tooling/bin/verify-paths.sh

fix-paths-safe:
	@./tooling/bin/fix-paths-safe.sh

verify-ui-cli:
	@./tooling/bin/verify-ui-cli.sh

builder-brief:
	@./tooling/bin/builder-brief.sh

adoption-brief:
	@./tooling/bin/adoption-brief.sh

release-brief:
	@./tooling/bin/release-brief.sh

new-repo-brief:
	@./tooling/bin/new-repo-brief.sh

onboarding-brief:
	@./tooling/bin/onboarding-brief.sh
