name: Tooling / Dependency Submission

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  submit-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        # v4
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false
      - name: Submit dependency graph
        # v0.0.7
        uses: advanced-security/component-detection-dependency-submission-action@9c110eb34dee187cd9eca76a652b9f6a0ed22927
        with:
          detectors: UvLock=EnableIfDefaultOff
